# Site settings
title: Machine Learning and Adaptive Intelligence 2014
email: N.Lawrence@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Module on machine learning and Adaptive Intelligence as taught in 2014.
baseurl: "/mlai2014/" # the subpath of your site, e.g. /blog/
url: "http://inverseprobability.com/" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  lawrennd

# Build settings
markdown: kramdown
